# Generated by Django 5.2.1 on 2025-05-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="matches/")),
                ("ticket_price", models.PositiveIntegerField()),
            ],
        ),
    ]
