# Generated by Django 5.2.1 on 2025-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
