# Generated by Django 5.2.1 on 2025-05-23 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_alter_match_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="end_time",
           field=models.TimeField(default="21:15:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="start_time",
            field=models.TimeField(default="19:15:00"),
            preserve_default=False,
        ),
    ]
