# Generated by Django 5.2.1 on 2025-05-23 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_match_end_time_match_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="end_time",
            field=models.TimeField(default=datetime.time(21, 15)),
        ),
        migrations.AlterField(
            model_name="match",
            name="start_time",
            field=models.TimeField(default=datetime.time(19, 15)),
        ),
    ]
