# Generated by Django 5.2.1 on 2025-05-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="seat_number",
            field=models.CharField(
                choices=[
                    ("A2", "Khán đài A2"),
                    ("A3", "Khán đài A3"),
                    ("A4", "Khán đài A4"),
                    ("A5", "Khán đài A5"),
                    ("B", "Khán đài B"),
                    ("C", "Khán đài C"),
                    ("D", "Khán đài D"),
                ],
                max_length=2,
            ),
        ),
    ]
