# Generated by Django 5.2.1 on 2025-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_ticket_date_alter_ticket_match_alter_ticket_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
